### ISSUE TITLE
Option to get all links, regardless of tag?

### ISSUE THREAD

**Issue by dylan-k** [snaptortoise/jekyll-pinboard-plugin#1]
This looks like a really useful thing. Thank you for making it!
I have a lot of links, with many tags, and I never know what I might tag next. Still, I'd like to be able to grab everything, for a links page, or an RSS feed, and have it available, regardless of the tags. Would this be possible here?

**Comment by georgemandis** [comment]
Thanks. Glad you like it :)

The plugin as-written isn't setup to load all the bookmarks like that, but the API seems to allow it:

[https://pinboard.in/api/#posts_all](https://pinboard.in/api/#posts_all)

I would want to change things so that instead of storing the tags at `site.pinboard.data['tag']` things were stored like this:

`site.pinboard.posts.tags['travel']` : All of the bookmarks tagged `travel`
`site.pinboard.posts.all` : All of the bookmarks in general

Using `site.pinboard.posts` this way instead of `site.pinboard.data` would also make it more consistent with the way the [API](https://pinboard.in/api/) is described. Maybe eventually I could pull in other parts of it.

I would  put in some backwards compatibility that maps `data` to `posts.tags` so this isn't a breaking change, for now, even though I think very few people are using the plugin right now.

Any thoughts on that approach? Does it make sense?

**Comment by georgemandis** [comment]
I've updated the plugin and in 0.2.0 you can now get all of the tags, per the structure I outlined in the previous comment here. It looks like a better setup to me anyhow as it more closely resembles the Pinboard API.

Thanks for the suggestion!
